backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: "https://maurocamisetasoficial.netlify.app"

collections:
  - name: "productos"
    label: "Productos"
    folder: "content/productos"
    create: true
    format: "json"
    slug: "{{slug}}"
    fields:
      - label: "Nombre del producto"
        name: "nombre"
        widget: "string"
      - label: "Club"
        name: "club"
        widget: "string"
      - label: "Etiqueta"
        name: "etiqueta"
        widget: "select"
        required: false
        options:
          - { label: "Ninguna", value: "" }
          - { label: "Nuevo", value: "Nuevo" }
          - { label: "Promo", value: "Promo" }
        default: ""
      - label: "Precio"
        name: "precio"
        widget: "number"
        value_type: "float"
        min: 0
      - label: "Talles disponibles"
        name: "talles"
        widget: "list"
        field:
          label: "Talle"
          name: "talle"
          widget: "string"
      - label: "Descripción"
        name: "descripcion"
        widget: "text"
      - label: "Imágenes del producto"
        name: "imagenes"
        widget: "list"
        field:
          label: "Imagen"
          name: "imagen"
          widget: "image"
      - label: "Enlace a WhatsApp"
        name: "whatsapp"
        widget: "string"
        default: "https://api.whatsapp.com/send/?phone=5493794040324&text=Hola%2C+quisiera+información+sobre&type=phone_number&app_absent=0"
      - label: "Enlace a Instagram"
        name: "instagram"
        widget: "string"
        default: "https://www.instagram.com/mauro.camisetas.oficial"

  - name: "catalogo"
    label: "Catálogo (lista única)"
    files:
      - file: "content/catalogo.json"
        label: "Listado de productos"
        name: "listado"
        format: "json"
        fields:
          - label: "Productos"
            name: "items"
            widget: "list"
            summary: "{{fields.nombre}} ({{fields.club}})"
            fields:
              - label: "Nombre"
                name: "nombre"
                widget: "string"
              - label: "Club"
                name: "club"
                widget: "string"
              - label: "Etiqueta"
                name: "etiqueta"
                widget: "select"
                required: false
                options:
                  - { label: "Ninguna", value: "" }
                  - { label: "Nuevo", value: "Nuevo" }
                  - { label: "Promo", value: "Promo" }
                default: ""
              - label: "Precio"
                name: "precio"
                widget: "number"
                value_type: "float"
                min: 0
              - label: "Talles"
                name: "talles"
                widget: "list"
                field:
                  label: "Talle"
                  name: "talle"
                  widget: "string"
              - label: "Descripción"
                name: "descripcion"
                widget: "text"
              - label: "Imágenes"
                name: "imagenes"
                widget: "list"
                field:
                  label: "Imagen"
                  name: "imagen"
                  widget: "image"
              - label: "WhatsApp"
                name: "whatsapp"
                widget: "string"
                default: "https://api.whatsapp.com/send/?phone=5493794040324&text=Hola%2C+quisiera+información+sobre&type=phone_number&app_absent=0"
              - label: "Instagram"
                name: "instagram"
                widget: "string"
                default: "https://www.instagram.com/mauro.camisetas.oficial"
